### ISSUE TITLE
Marker Icon / Font Awesome / Minecraft resource pack font conversion?

### ISSUE THREAD

**Issue by ryantheleach** [SentixDev/Pl3xMap-Marker#6]
This looks pretty nice, but it would be cool to see some emoji / font awesome / icon support of some kind.

Apologies if this is already implemented, I was basing it off a quick glance on plugin homepage on spigot.

**Comment by SentixDev** [comment]
You can add custom icons per marker. You simply do that by uploading your icon to the service of your choice and add the url on marker creation. Since this plugin is a Java plugin and I'm only using the API of Pl3xMap, I basically can't add any additional styling to the website components, beside the fact that players can customize the marker-tooltips with HTML tags. If you want font-awesome support you should ask the maintainers of the Pl3xMap fork of your choice.
